### ISSUE TITLE
Install using Conda and pip - pymoab is not included

### ISSUE THREAD

**Issue by msavtchouk-pf** [fusion-energy/cad_to_dagmc#55]
Hi all!
I am trying to follow the installation instructions here:
https://pypi.org/project/cad-to-dagmc/

Install using Conda and pip
However, when I run a simple script 

`
import cad_to_dagmc
`

I have the following error:

Traceback (most recent call last):
  File "/home/marija/main.py", line 1, in <module>
    import cad_to_dagmc
  File "/usr/local/bin/conda/envs/env_d/lib/python3.10/site-packages/cad_to_dagmc/__init__.py", line 16, in <module>
    from .core import *
  File "/usr/local/bin/conda/envs/env_d/lib/python3.10/site-packages/cad_to_dagmc/core.py", line 10, in <module>
    from pymoab import core, types
ModuleNotFoundError: No module named 'pymoab'

Have anyone seen it before? Are there extra installation steps needed?

**Comment by shimwell** [comment]
That is strange the ```pymoab``` package should arrive when ```moab``` is installed.

Did you run this part of the install instructions
```
mamba install -c cadquery -c conda-forge moab gmsh python-gmsh cadquery=master -y
```

**Comment by shimwell** [comment]
I've just updated the instructions as cadquery 2.4.0 is now on conda forge, so the above install line can now be shortened to

```
mamba install -c conda-forge moab gmsh python-gmsh cadquery -y
```

**Comment by msavtchouk-pf** [comment]
I did run the command to install the dependencies (although with conda, not mamba)

The import worked when specific versions of packages were installed:

 2174  conda create -n envname python=3.10 -y
 2175  conda activate envname 
 2176  pip install cad_to_dagmc==0.5.1 cadquery==2.4.0
 2177  mamba install openmc=0.14.0
 2178  mamba install gmsh=4.12.2
 2186  mamba install python-gmsh=4.12.2 
 
 Here it seems that pymob was installed with openmc.

**Comment by shimwell** [comment]
closing as solved, also for anyone reading this we also no default to a h5py route that no longer needs pymoab
